name: Customized Bundle Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-registry:
    runs-on: macos-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: Test registry
        run: yarn add @gadget-client/collection-testing@latest
